# Generated by Django 4.1.9 on 2023-06-02 13:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default=accounts.models.get_default_image, upload_to="images/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="Nick", max_length=125),
        ),
    ]
